nginx:
  environment:
    - SYMFONY_ENV=dev
  image: "ngnix:latest"
  build: docker/nginx
  env_file:
    - .env
  ports:
    - 81:80
  links:
    - php
    - mysql
  volumes:
    - ./:/var/www/symfony/
